gitlab:
  image: 'gitlab/gitlab-ce:11.1.4-ce.0'
  restart: always
  hostname: 'gitlab.11-1-4.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.11-1-4.com'
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
